/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF, useTexture } from '@react-three/drei';

const FLOAT_SPEED = 1.2;
const FLOAT_AMPLITUDE = 0.35;
const ROTATION_SPEED = 0.8;
const BASE_ROTATION = [2.6, 0.8, -1.8];

const Cube = ({ position = [9, -4, 0], ...props }) => {
  const { nodes } = useGLTF('/models/cube.glb');
  const texture = useTexture('/textures/cube.png');
  const groupRef = useRef();
  const shiftedPosition = useMemo(() => [position[0] + 1.5, position[1], position[2]], [position]);

  useFrame(({ clock }) => {
    if (!groupRef.current) return;

    const t = clock.getElapsedTime();
    groupRef.current.position.set(
      shiftedPosition[0],
      shiftedPosition[1] + Math.sin(t * FLOAT_SPEED) * FLOAT_AMPLITUDE,
      shiftedPosition[2],
    );
    groupRef.current.rotation.set(
      BASE_ROTATION[0] + Math.sin(t * FLOAT_SPEED) * 0.08,
      BASE_ROTATION[1] + t * ROTATION_SPEED,
      BASE_ROTATION[2],
    );
  });

  return (
    <group ref={groupRef} scale={0.74} dispose={null} {...props}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={nodes.Cube.material}>
        <meshMatcapMaterial matcap={texture} toneMapped={false} />
      </mesh>
    </group>
  );
};

useGLTF.preload('/models/cube.glb');
useTexture.preload('/textures/cube.png');

export default Cube;
