
// // Auto - generated by: https://github.com/pmndrs/gltfjsx
// // Author: kraytay(https://sketchfab.com/lokikikiko75)
// //   License: CC - BY - 4.0(http://creativecommons.org/licenses/by/4.0/)
// //     Source: https://sketchfab.com/3d-models/cyber-tank-futuristiccyberpunk-8882ab6534e14ce6b09ed9cd65206290
// //     Title: Cyber Tank(Futuristic / Cyberpunk)
// //   */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// const Target=(props) => {
//   const { nodes, materials } = useGLTF('/scene.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.376}>
//         <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube081_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-371.287, -172.178, 496.859]}
//             scale={[0.011, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube012_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-485.102, -172.339, 496.879]}
//             scale={[0.01, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube022_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 44.932, -612.009]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube019_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 121.667, -562.668]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube034_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-221.629, -26.43, -642.017]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube054_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -222.477, 731.655]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube072_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -242.258]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube023_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 355.607, -342.053]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube020_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 76.046, -590.647]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube035_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-230.133, -67.759, -630.12]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder001_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-147.872, 22.468, 357.308]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube073_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -150.542]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder035_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-365.474, -145.317, 736.277]}
//             rotation={[1.925, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube005_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -13.383, -367.167]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube024_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 49.264, -625.017]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder012_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-211.999, -110.06, -639.124]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder023_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-102.244, 22.469, 357.308]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube074_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 8.38, 595.697]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder036_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-479.071, -145.317, 736.277]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder013_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-242.005, -110.06, -639.124]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube055_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, 25.607, 391.475]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube075_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -166.28, -399.772]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube036_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-84.308, -172.26, -629.643]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder024_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-56.657, 30.438, 366.27]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube076_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -52.095, 591.225]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder037_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-427.329, -177, 347.375]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube029_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 102.093, -423.618]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube037_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-56.146, -27.511, -645.948]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder025_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.954, 43.725, -160.592]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube077_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -222.588, 701.476]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube083_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-381.68, -155.651, -354.849]}
//             scale={[0.011, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube004_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -16.364, -596.53]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube028_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 102.906, -359.032]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube038_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-67.907, -27.511, -645.948]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder026_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.954, 43.725, -129.692]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube078_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -166.28, 582.335]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder038_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-440.462, -158.992, -266.083]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube007_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -63.919, 186.111]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder007_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 110.925, -305.56]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder014_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-62.026, -24.941, -666.312]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube056_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -593.923]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus005_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-40.342, 50.356, 96.477]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube006_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -11.483, -134.153]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube030_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 101.532, -339.859]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder015_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-137.932, -223.527, -642.2]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube057_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 32.017, -17.707]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus006_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.709, -13.433, 511.266]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder039_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-378.607, -127.309, -114.23]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder006_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 121.992, -488.566]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube027_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 102.906, -456.757]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube039_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-138.006, -244.352, -684.087]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube058_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 47.803, 20.854]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube084_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 31.083, 452.264]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder040_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-492.204, -127.309, -114.23]}
//             rotation={[1.925, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube026_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 114.732, -444.951]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder016_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[102.658, -223.811, -642.775]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube059_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 4.31, -54.702]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube085_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 34.83, 452.264]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube088_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-495.536, -155.659, -354.837]}
//             scale={[0.01, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder041_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-440.462, -158.992, -511.022]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder004_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 111.994, -420.663]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube025_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -0.182, -680.452]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube040_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[102.892, -245.067, -684.372]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder027_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 50.417, 397.164]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube086_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 31.083, 419.828]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder005_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 111.994, -389.763]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder008_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 18.794, -696.719]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder017_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-227.108, -174.356, -659.578]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube060_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-20.495, -79.187, 623.733]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube087_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 34.83, 419.828]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube017_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 365.518, -532.849]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus001_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-133.908, -100.669, -634.177]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube061_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -44.372, 640.85]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Plane_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -146.601, -200.67]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube089_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-64.518, 268.183, 137.479]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube021_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 44.932, -612.009]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube032_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 101.457, -369.649]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube041_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[23.226, -85.104, -644.1]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube062_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 6.139, 574.371]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Plane001_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -114.332, 405.061]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder003_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 335.664, -342.053]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube042_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[11.465, -85.104, -644.1]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder028_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 2.786, 569.819]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube090_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 237.916, -658.964]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder042_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[382.805, -177, 558.641]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube016_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 348.05, -547.142]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube043_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[23.226, -170.835, -644.1]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder029_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 2.786, 569.819]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube079_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[86.539, 323.148, -174.48]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube014_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.528, -66.963, 519.174]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube044_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[11.465, -170.835, -644.1]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder030_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 2.786, 569.819]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube080_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[86.539, 328.437, -174.48]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder043_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[444.66, -145.317, 728.001]}
//             rotation={[1.925, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube015_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-24.131, 285.659, -207.623]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube045_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[17.345, -127.885, -649.764]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube063_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 21.357, 484.047]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube082_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-204.419, 319.67, -304.899]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder044_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[331.063, -145.317, 728.001]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder011_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[212.303, -122.275, -622.674]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube064_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 21.357, 489.63]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube091_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[159.904, 328.437, -233.272]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube013_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.591, -122.873, 587.694]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder002_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 90.596, -595.864]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder018_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[215.748, -201.087, -619.638]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube065_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -175.002, 624.055]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube092_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[159.522, 323.148, -234.134]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder045_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[382.805, -177, 342.544]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube011_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-20.268, -152.636, 527.47]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus002_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[41.145, -41.385, -631.507]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder031_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-20.304, -205.473, 608.468]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube095_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[447.17, -155.651, -354.849]}
//             scale={[0.011, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube046_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -75.251, -674.278]}
//             rotation={[1.82, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube066_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 34.902, 286.057]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder033_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-64.518, 268.184, -28.417]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder046_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[388.388, -158.992, -266.083]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube008_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -91.669, 445.415]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube050_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 18.434, -664.101]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder032_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 45.189, 286.097]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder034_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-427.329, -177, 563.472]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube010_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 6.139, 574.371]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube051_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-14.765, 4.983, -636.215]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus003_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 50.356, 96.477]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 105.389, -228.569]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube096_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[333.314, -155.659, -354.837]}
//             scale={[0.01, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder019_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[212.379, 2.574, -627.809]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube067_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 48.489, 76.14]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire002_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 104.673, -355.05]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder047_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[388.388, -158.992, -511.022]}
//             rotation={[1.925, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[25.34, 36.835, -416.258]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube031_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 105.204, -339.859]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder020_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[115.096, 2.574, -627.809]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube068_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 47.837, 53.853]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire003_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[164.272, 2.481, -643.502]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder048_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[435.272, -127.309, -114.23]}
//             rotation={[1.925, 0, 0]}
//             scale={0.005}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.081, 93.63, 139.126]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube033_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 105.204, -369.649]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder021_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[212.379, -21.493, -627.809]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Torus004_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 19.266, 516.067]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire004_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[164.272, -21.909, -643.502]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder009_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.629, -50.046, 589.046]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder022_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[115.096, -21.493, -627.809]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube069_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -501.074]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire005_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-23.148, 93.573, 205.617]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube001_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 3.541, -422.103]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cylinder010_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-19.594, -113.933, 693.737]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube052_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 129.576, -566.415]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube070_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -413.755]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire006_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 34.299, 436.213]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube009_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.895, 176.265, -340.579]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube002_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, -7.045, -452.659]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube053_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 128.447, -561.765]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube071_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 9.583, -327.692]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire007_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[123.601, 327.688, -203.701]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube018_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 121.667, -562.668]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube003_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-21.955, 334.044, -470.862]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Fluent_Wire008_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[-20.548, 369.354, -341.052]}
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube093_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[439.36, -176.559, 495.673]}
//             scale={[0.011, 0.013, 0.013]}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube094_CyberTANK_0.geometry}
//             material={materials.CyberTANK}
//             position={[325.545, -176.72, 495.694]}
//             scale={[0.01, 0.013, 0.013]}
//           />
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/assets/scene.gltf')

// export default Target;
import React from 'react';

const Target = (props) => {
  return (
    <mesh {...props} castShadow receiveShadow>
      <icosahedronGeometry args={[1, 0]} />
      <meshStandardMaterial color="#ef4444" metalness={0.2} roughness={0.4} />
    </mesh>
  );
};

export default Target;
